### ISSUE TITLE
Map BRMA to region

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk#786]
So we can assign BRMAs within region for LHA

**Comment by MaxGhenis** [comment]
[Thanks, ChatGPT!](https://chat.openai.com/share/c5a4a089-4276-46ec-ae7c-6b92d869e84b) I spot-checked a few and they all looked right.
```yaml
BRMA_to_Region:
  Ashford: "South East"
  Aylesbury: "South East"
  Barnsley: "Yorkshire and the Humber"
  Barrow_in_Furness: "North West"
  Basingstoke: "South East"
  Bath: "South West"
  Bedford: "East of England"
  Birmingham: "West Midlands"
  Black_Country: "West Midlands"
  Blackwater_Valley: "South East"
  Bolton_and_Bury: "North West"
  Bournemouth: "South West"
  Bradford_South_Dales: "Yorkshire and the Humber"
  Brighton_and_Hove: "South East"
  Bristol: "South West"
  Bury_St_Edmunds: "East of England"
  Cambridge: "East of England"
  Canterbury: "South East"
  Central_Greater_Manchester: "North West"
  Central_Lancs: "North West"
  Central_London: "London"
  Central_Norfolk_Norwich: "East of England"
  Chelmsford: "East of England"
  Cheltenham: "South West"
  Cherwell_Valley: "South East"
  Chesterfield: "East Midlands"
  Chichester: "South East"
  Chilterns: "South East"
  Colchester: "East of England"
  Coventry: "West Midlands"
  Crawley_Reigate: "South East"
  Darlington: "North East"
  Derby: "East Midlands"
  Doncaster: "Yorkshire and the Humber"
  Dover_Shepway: "South East"
  Durham: "North East"
  East_Cheshire: "North West"
  East_Lancs: "North West"
  East_Thames_Valley: "South East"
  Eastbourne: "South East"
  Eastern_Staffordshire: "West Midlands"
  Exeter: "South West"
  Fylde_Coast: "North West"
  Gloucester: "South West"
  Grantham_Newark: "East Midlands"
  Greater_Liverpool: "North West"
  Grimsby: "Yorkshire and the Humber"
  Guildford: "South East"
  Halifax: "Yorkshire and the Humber"
  Harlow_Stortford: "East of England"
  Harrogate: "Yorkshire and the Humber"
  Herefordshire: "West Midlands"
  High_Weald: "South East"
  Hull_East_Riding: "Yorkshire and the Humber"
  Huntingdon: "East of England"
  Inner_East_London: "London"
  Inner_North_London: "London"
  Inner_South_East_London: "London"
  Inner_South_West_London: "London"
  Inner_West_London: "London"
  Ipswich: "East of England"
  Isle_of_Wight: "South East"
  Kendal: "North West"
  Kernow_West: "South West"
  Kings_Lynn: "East of England"
  Kirklees: "Yorkshire and the Humber"
  Lancaster: "North West"
  Leeds: "Yorkshire and the Humber"
  Leicester: "East Midlands"
  Lincoln: "East Midlands"
  Lincolnshire_Fens: "East Midlands"
  Lowestoft_Great_Yarmouth: "East of England"
  Luton: "East of England"
  Maidstone: "South East"
  Medway_Swale: "South East"
  Mendip: "South West"
  Mid_East_Devon: "South West"
  Mid_West_Dorset: "South West"
  Mid_Staffs: "West Midlands"
  Milton_Keynes: "South East"
  Newbury: "South East"
  North_Cheshire: "North West"
  North_Cornwall_Devon_Borders: "South West"
  North_Cumbria: "North West"
  North_Devon: "South West"
  North_Nottingham: "East Midlands"
  North_West_Kent: "South East"
  North_West_London: "London"
  Northampton: "East Midlands"
  Northants_Central: "East Midlands"
  Northumberland: "North East"
  Nottingham: "East Midlands"
  Oldham_Rochdale: "North West"
  Outer_East_London: "London"
  Outer_North_East_London: "London"
  Outer_North_London: "London"
  Outer_South_East_London: "London"
  Outer_South_London: "London"
  Outer_South_West_London: "London"
  Outer_West_London: "London"
  Oxford: "South East"
  Peaks_Dales: "East Midlands"
  Peterborough: "East of England"
  Plymouth: "South West"
  Portsmouth: "South East"
  Reading: "South East"
  Richmond_Hambleton: "Yorkshire and the Humber"
  Rotherham: "Yorkshire and the Humber"
  Rugby_East: "West Midlands"
  Salisbury: "South West"
  Scarborough: "Yorkshire and the Humber"
  Scunthorpe: "Yorkshire and the Humber"
  Sheffield: "Yorkshire and the Humber"
  Shropshire: "West Midlands"
  Solihull: "West Midlands"
  South_Cheshire: "North West"
  South_Devon: "South West"
  South_East_Herts: "East of England"
  South_West_Essex: "East of England"
  South_West_Herts: "East of England"
  Southampton: "South East"
  Southend: "East of England"
  Southern_Greater_Manchester: "North West"
  Southport: "North West"
  St_Helens: "North West"
  Staffordshire_North: "West Midlands"
  Stevenage_North_Herts: "East of England"
  Sunderland: "North East"
  Sussex_East: "South East"
  Swindon: "South West"
  Tameside_Glossop: "North West"
  Taunton_West_Somerset: "South West"
  Teesside: "North East"
  Thanet: "South East"
  Tyneside: "North East"
  Wakefield: "Yorkshire and the Humber"
  Walton: "South East"
  Warwickshire_South: "West Midlands"
  West_Cheshire: "North West"
  West_Cumbria: "North West"
  West_Pennine: "North West"
  West_Wiltshire: "South West"
  Weston_S_Mare: "South West"
  Wigan: "North West"
  Winchester: "South East"
  Wirral: "North West"
  Wolds_and_Coast: "Yorkshire and the Humber"
  Worcester_North: "West Midlands"
  Worcester_South: "West Midlands"
  Worthing: "South East"
  Yeovil: "South West"
  York: "Yorkshire and the Humber"
  Belfast: "Northern Ireland"
  Lough_Neagh_Lower: "Northern Ireland"
  Lough_Neagh_Upper: "Northern Ireland"
  North_NI: "Northern Ireland"
  North_West_NI: "Northern Ireland"
  South_NI: "Northern Ireland"
  South_East_NI: "Northern Ireland"
  South_West_NI: "Northern Ireland"
```
